
project_id = "uuosgyvftjurmeqwxvvi"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[functions.cancel-subscription]
verify_jwt = false
