
project_id = "uuosgyvftjurmeqwxvvi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = false

[inbucket]
enabled = false

[studio]
enabled = false

[functions.paypal-subscription]
verify_jwt = true
