// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuosgyvftjurmeqwxvvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1b3NneXZmdGp1cm1lcXd4dnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjcyNzMsImV4cCI6MjA2MTk0MzI3M30.4HvQuzM987gYfOsm0-I9EwWygVNB8NXp4Nh82E8r3MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);